# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f95851acc98a659787ce958fa628d5d58825c6094712758f52386596364358bba1770f24b17d6480db300ed5ae8dfb6d8132d0b5dcc0db25300610507907888

test:
  secret_key_base: d5e0c32193022eeb7214bd0b48487bcef97145f58235c21345718025faa42e97554fb310feb708d5fd1aa0046a20ef79de5690b7cc8b266c0f291aa1725d2afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
